apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../general
# Istio
- ../manifests/common/istio-1-17/istio-crds/base
- ../manifests/common/istio-1-17/istio-namespace/base
- ../manifests/common/istio-1-17/istio-install/base
# OIDC Authservice
- ../manifests/common/oidc-client/oidc-authservice/base
# Dex
- ../manifests/common/dex/overlays/istio
# KNative
- ../manifests/common/knative/knative-serving/overlays/gateways
- ../manifests/common/knative/knative-eventing/base
- ../manifests/common/istio-1-17/cluster-local-gateway/base
# Kubeflow Istio Resources
- ../manifests/common/istio-1-17/kubeflow-istio-resources/base

# KServe
- ../manifests/contrib/kserve/kserve
- ../manifests/contrib/kserve/models-web-app/overlays/kubeflow

patches:
- path: ./kserve-models-web-app-patch.yaml
  target:
    kind: Deployment
- path: ./kserve-controller-manager-patch.yaml
  target:
    kind: Deployment
- path: ./cert-manager-patch.yaml
  target:
    kind: Deployment
- path: ./dex-patch.yaml
  target:
    kind: Deployment
- path: ./istio-nodepool-patch.yaml
  target:
    kind: Deployment
- path: ./knative-patch.yaml
  target:
    kind: Deployment
- path: ./istio-webhook-aks-patch.yaml

patchesJson6902:
  - target:
      group: autoscaling
      version: v2beta2
      kind: 'HorizontalPodAutoscaler'
      name: '.*'
    patch: |-
      - op: replace
        path: "/apiVersion"
        value: autoscaling/v2

configMapGenerator:
  - name: kserve-models-web-app-config
    behavior: replace
    literals:
    - APP_PREFIX=/
    - APP_DISABLE_AUTH="True"
    - APP_SECURE_COOKIES="False"
