apiVersion: v1
kind: Secret
metadata:
  name: azcreds
type: Opaque
stringData: # use `stringData` for raw credential string or `data` for base64 encoded string
  AZ_CLIENT_ID: "<client_id>"
  AZ_CLIENT_SECRET: "<client_secret>"
  AZ_SUBSCRIPTION_ID: "<subscription_id>"
  AZ_TENANT_ID: "<tenant_id>"

