apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../general

# Training Operator (the main component for managing training jobs)
- ../manifests/apps/training-operator/upstream/overlays/kubeflow

patches:
- path: ./training-operator-patch.yaml
  target:
    kind: Deployment